### PR TITLE
Updated mappings to official 1.16.5

### PR DESCRIPTION
**Pull request by muqsit-0010**
Updated mappings to official 1.16.5
MC version 1.16.5
Forge Version >= 36

I was experimenting with the new mappings on your mod.
I realized that the project has been stale for the better part of a year so you maybe planning to update the mappings before continuation. 
I have pushed the updates and this pull request just in case to save you from the trouble of having to update the mappings, when I have already done so.

If you do not plan on updating the mappings, kindly disregard the pull request.

### CODE REVIEW

**Comment by gigaherz** [comment]
Hi, thanks for the PR but I'm wondering why you thought it was necessary? My plan was to update as part of porting to 1.17, whenever that's released, instead of introducing unnecessary noise in the middle of a version.

**Comment by AbdulMuqsit** [comment]
Ah, my bad. Sounds like a good plan.
I updated the original with what I had in my mind when creating the pull request.

**Comment by gigaherz** [comment]
I just read what you edited in the original message.
"has been stale for the better part of a year " is just simply not true. There's commits from literally 3 days ago, and before that, I did merge a PR back in january. XD
It is true that I haven't released an update in a bit, but "in a bit" is just a few months, because I have been busy moving and working on other mods (I have a bunch).
Anyhow I don't want to just outright reject the PR, I *may* decide to update the mappings at a later date, I just happen to have other priorities than getting used to mojang names right now.

**Comment by AbdulMuqsit** [comment]
Understandable, no problem.

**Comment by gigaherz** [comment]
The update to 1.17.1 included the switch to official names, so this is effectively done. :)

**Pull request closed without merging**
